/*
Developer: Sasha Comstock
Date: May 16, 2020
Description: The Ratings dimension contains granular voting details which are leveraged to determine movie ratings
*/
CREATE TABLE `dim_Ratings` (
    `Ratings_id` INT NOT NULL AUTO_INCREMENT,
    `imdb_title_id` VARCHAR(20),
    `weighted_average_vote` DECIMAL(18,4) DEFAULT NULL,
    `total_votes` INT DEFAULT NULL,
    `mean_vote` DECIMAL(18,4) DEFAULT NULL,
    `median_vote` DECIMAL(18,4) DEFAULT NULL,
    `votes_10` INT DEFAULT NULL,
    `votes_9` INT DEFAULT NULL,
    `votes_8` INT DEFAULT NULL,
    `votes_7` INT DEFAULT NULL,
    `votes_6` INT DEFAULT NULL,
    `votes_5` INT DEFAULT NULL,
    `votes_4` INT DEFAULT NULL,
    `votes_3` INT DEFAULT NULL,
    `votes_2` INT DEFAULT NULL,
    `votes_1` INT DEFAULT NULL,
    `allgenders_0age_avg_vote` DECIMAL(18,4) DEFAULT NULL,
    `allgenders_0age_votes` INT DEFAULT NULL,
    `allgenders_18age_avg_vote` DECIMAL(18,4) DEFAULT NULL,
    `allgenders_18age_votes` INT DEFAULT NULL,
    `allgenders_30age_avg_vote` DECIMAL(18,4) DEFAULT NULL,
    `allgenders_30age_votes` INT DEFAULT NULL,
    `allgenders_45age_avg_vote` DECIMAL(18,4) DEFAULT NULL,
    `allgenders_45age_votes` INT DEFAULT NULL,
    `males_allages_avg_vote` DECIMAL(18,4) DEFAULT NULL,
    `males_allages_votes` INT DEFAULT NULL,
    `males_0age_avg_vote` DECIMAL(18,4) DEFAULT NULL,
    `males_0age_votes` INT DEFAULT NULL,
    `males_18age_avg_vote` DECIMAL(18,4) DEFAULT NULL,
    `males_18age_votes` INT DEFAULT NULL,
    `males_30age_avg_vote` DECIMAL(18,4) DEFAULT NULL,
    `males_30age_votes` INT DEFAULT NULL,
    `males_45age_avg_vote` DECIMAL(18,4) DEFAULT NULL,
    `males_45age_votes` INT DEFAULT NULL,
    `females_allages_avg_vote` DECIMAL(18,4) DEFAULT NULL,
    `females_allages_votes` INT DEFAULT NULL,
    `females_0age_avg_vote` DECIMAL(18,4) DEFAULT NULL,
    `females_0age_votes` INT DEFAULT NULL,
    `females_18age_avg_vote` DECIMAL(18,4) DEFAULT NULL,
    `females_18age_votes` INT DEFAULT NULL,
    `females_30age_avg_vote` DECIMAL(18,4) DEFAULT NULL,
    `females_30age_votes` INT DEFAULT NULL,
    `females_45age_avg_vote` DECIMAL(18,4) DEFAULT NULL,
    `females_45age_votes` INT DEFAULT NULL,
    `top1000_voters_rating` DECIMAL(18,4) DEFAULT NULL,
    `top1000_voters_votes` INT DEFAULT NULL,
    `us_voters_rating` DECIMAL(18,4) DEFAULT NULL,
    `us_voters_votes` INT DEFAULT NULL,
    `non_us_voters_rating` DECIMAL(18,4) DEFAULT NULL,
    `non_us_voters_votes` INT DEFAULT NULL,
    PRIMARY KEY (Ratings_id)
    --CONSTRAINT imdb_title_id_pk PRIMARY KEY (imdb_title_id)
  ) ;
